import { IUser } from '../types';

export let users: IUser[] = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    firstNameKana: 'John',
    lastNameKana: 'Doe',
    email: 'johndoe@gmail.com',
    phoneNumber: '123456789',
    gender: 'male',
    newsletterSuscribed: true,
    newsletterPartnersSuscribed: true,
    password: 'asdfghjk',
    birthDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 2,
    firstName: 'Erica',
    lastName: 'Doe',
    firstNameKana: 'Erica',
    lastNameKana: 'Doe',
    email: 'ericadoe@gmail.com',
    phoneNumber: '123456789',
    gender: 'female',
    newsletterSuscribed: false,
    newsletterPartnersSuscribed: false,
    password: 'asdfghjk',
    birthDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: 3,
    firstName: 'Jane',
    lastName: 'Doe',
    firstNameKana: 'Jane',
    lastNameKana: 'Doe',
    email: 'janedoe@gmail.com',
    phoneNumber: '123456789',
    gender: 'female',
    newsletterSuscribed: true,
    newsletterPartnersSuscribed: true,
    password: 'asdfghjk',
    birthDate: new Date(),
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];
